/*
   Sábado, 13 de Marzo de 2010 09:00:57 p.m.
   Usuario: 
   Servidor: (LOCAL)
   Base de datos: SistemaNominaNorteak
   Aplicación: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.DatosEmpresa ADD
	TipoCalculoIR nvarchar(50) NULL
GO
COMMIT
